Repository oduck-team/oduck-client, pull requests merged in 2023-11, with the labels that each got.

#263 feat: 애니 등록 공개 여부 추가, 이미지 등록후 반환 url 수정
  src/admins/features/animes/api/AdminAnimeApi.ts
  src/admins/features/animes/components/AdminCreateAnimeForm.tsx
  src/admins/features/animes/components/AnimePreviewCard.style.ts
  src/admins/features/animes/components/AnimePreviewCard.tsx
  src/admins/features/animes/hooks/useCreateAnime.ts
  src/components/Layout/Sidebar.tsx
  src/features/files/api/FileApi.ts
  src/libs/api/index.ts
Labels: feature, refactor

#260 feat: 프로필 페이지 접근 권한 처리
  src/admins/components/Layouts/AdminLayout.tsx
  src/components/Layout/Sidebar.tsx
  src/features/auth/contexts/AuthContext.tsx
  src/features/users/api/profile.ts
  src/features/users/routes/Profile/index.tsx
  src/routes/privateRoutes.tsx
  src/routes/publicRoutes.tsx
  src/types/business.d.ts
Labels: feature

#264 feat: Toast 컴포넌트 구현
  src/App.tsx
  src/components/SnackBar/style.ts
  src/components/Toast/ToastPortal.tsx
  src/components/Toast/index.tsx
  src/components/Toast/style.ts
  src/components/Toast/useToast.ts
  src/contexts/ToastContext.tsx
  src/styles/colors.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: feature

#257 feat: 리뷰 작성 구현
  src/components/SnackBar/SnackBarPortal.tsx
  src/components/SnackBar/style.ts
  src/components/Toast/style.ts
  src/contexts/OduckApiContext.tsx
  src/features/reviews/api/review.ts
  src/features/reviews/components/AttractionPoint/index.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewRating/ShortReviewModal.style.ts
  src/features/reviews/components/ReviewRating/ShortReviewModal.tsx
  src/features/reviews/components/ReviewRating/SpoilerCheckBox.tsx
  src/features/reviews/hook/useAddReview.ts
  src/features/reviews/hook/useReviewForm.tsx
Labels: feature

#266 feat: 프로필 페이지 변경사항 적용
  src/components/Layout/Sidebar.tsx
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/common/routes/Home/RecentReview/style.ts
  src/features/reviews/components/ReviewCard/ActionBar.style.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/ReviewLikeButton.style.ts
  src/features/reviews/components/ReviewCard/ReviewMoreButton.style.ts
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewCard/SpoilerComment.style.ts
  src/features/reviews/components/ReviewCard/SpoilerComment.tsx
  src/features/reviews/components/ReviewCard/index.tsx
  src/features/reviews/components/ReviewCard/style.ts
  src/features/users/api/mock/profile.json
  src/features/users/hooks/useTabMenu.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.style.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkDeleteModal.style.ts
  src/features/users/routes/Profile/TabMenu/BookmarkDeleteModal.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkList.tsx
  src/features/users/routes/Profile/TabMenu/EmptyList.style.ts
  src/features/users/routes/Profile/TabMenu/EmptyList.tsx
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
  src/features/users/routes/Profile/TabMenu/index.tsx
  src/features/users/routes/Profile/index.tsx
  src/routes/privateRoutes.tsx
  src/types/business.d.ts
Labels: feature

#267 feat: 이미지 업로드 압축
  package-lock.json
  package.json
  src/admins/components/Form/ImageDropzone.tsx
  src/admins/features/animes/components/EditVoiceActorsModal.style.ts
  src/admins/features/animes/components/EditVoiceActorsModal.tsx
  src/libs/compressor/index.ts
Labels: feature

#268 feat: 회원 프로필 수정 구현 및 로그인 리다이렉트 로직 수정
  src/admins/app/router.tsx
  src/components/Layout/ErrorBoundaryLayout/index.tsx
  src/components/Layout/RouteLayout/SavePath.tsx
  src/components/Layout/RouteLayout/index.tsx
  src/features/auth/hooks/useLogin.ts
  src/features/auth/routes/Login/index.tsx
  src/features/reviews/hook/useReviewForm.tsx
  src/features/users/api/profile.ts
  src/features/users/api/profileDev.ts
  src/features/users/hooks/useEditForm.ts
  src/features/users/hooks/useEditForm.tsx
  src/features/users/routes/Edit/index.tsx
  src/routes/privateRoutes.tsx
  src/routes/publicRoutes.tsx
Labels: feature

#269 feat: 애니 리스트, 애니 디테일 페이지 동적 데이터 사용 및 북마크 토글 구현
  src/components/Layout/Header/style.ts
  src/contexts/OduckApiContext.tsx
  src/features/animes/api/AnimeApi.ts
  src/features/animes/api/GenreApi.ts
  src/features/animes/components/AnimeCard/index.tsx
  src/features/animes/components/AnimeCard/style.ts
  src/features/animes/components/AnimeSlide/index.tsx
  src/features/animes/hooks/useAnime.ts
  src/features/animes/hooks/useAnimes.ts
  src/features/animes/hooks/useFilterAnimes.ts
  src/features/animes/routes/Detail/Hero/index.tsx
  src/features/animes/routes/Detail/PlotAndInfo/index.tsx
  src/features/animes/routes/Detail/index.tsx
  src/features/animes/routes/List/Filter/index.tsx
  src/features/animes/routes/List/index.tsx
  src/features/animes/routes/List/style.ts
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/bookmarks/hooks/useToggleBookmark.ts
  src/features/common/routes/Home/index.tsx
  src/features/common/routes/Search/index.tsx
  src/features/reviews/hook/useAddReview.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkDeleteModal.tsx
  src/types/business.d.ts
Labels: feature

#271 feat: 애니 리뷰 목록 조회 구현
  src/components/Toast/style.ts
  src/contexts/OduckApiContext.tsx
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/animes/routes/Detail/Reviews/style.ts
  src/features/animes/routes/Detail/index.tsx
  src/features/animes/routes/Detail/style.ts
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/reviews/api/mock/anime_review_list1.json
  src/features/reviews/api/mock/anime_review_list2.json
  src/features/reviews/api/mock/anime_review_list3.json
  src/features/reviews/api/mock/anime_review_list4.json
  src/features/reviews/api/review.ts
  src/features/reviews/api/reviewDev.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/ReviewLikeButton.style.ts
  src/features/reviews/components/ReviewCard/ReviewLikeButton.tsx
  src/features/reviews/components/ReviewCard/UserRating.tsx
  src/features/reviews/hook/useAddReview.ts
  src/features/reviews/hook/useGetAnimeReviews.ts
  src/features/reviews/hook/useReviewForm.tsx
  src/features/users/api/mock/review1.json
  src/features/users/api/mock/review2.json
  src/features/users/api/mock/review3.json
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
  src/types/business.d.ts
Labels: feature, refactor

#278 refactor: Toast 컴포넌트 개선
  src/components/Toast/useToast.tsx
Labels: refactor

#275 feat: 자주 사용되는 오류 toast 분리
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/reviews/hook/useReviewForm.tsx
  src/features/users/hooks/useEditForm.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkDeleteModal.tsx
  src/libs/error/index.tsx
Labels: feature, refactor

#280 feat: 프로필 페이지 변경사항 반영
  src/components/Loader/style.ts
  src/features/users/hooks/useEditForm.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkCard.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkDeleteModal.tsx
Labels: feature, fix

#282 feat: 애니 목록 조회에 장르 적용
  src/features/animes/hooks/useFilterAnimes.ts
  src/features/animes/hooks/useGenres.ts
  src/features/animes/routes/List/index.tsx
Labels: feature

#285 feat: 애니 상세페이지 리뷰 목록 스타일 수정 및 스켈레톤 추가
  src/components/Skeleton/index.tsx
  src/components/Skeleton/style.ts
  src/features/animes/routes/Detail/LoadingReviews/index.tsx
  src/features/animes/routes/Detail/LoadingReviews/style.ts
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/animes/routes/Detail/Reviews/style.ts
  src/features/animes/routes/Detail/index.tsx
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/reviews/api/review.ts
  src/features/reviews/components/ReviewCard/ActionBar.style.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/SpoilerComment.style.ts
  src/features/reviews/components/ReviewCard/UserRating.style.ts
  src/features/reviews/components/ReviewCard/style.ts
  src/features/reviews/hook/useReviewForm.tsx
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
Labels: feature, refactor

#287 feat: 관리자 성우, 원작자, 제작사, 장르, 시리즈 수정 삭제
  src/admins/features/animes/api/AdminGenreApi.ts
  src/admins/features/animes/api/AdminOriginalAuthorApi.ts
  src/admins/features/animes/api/AdminSeriesApi.ts
  src/admins/features/animes/api/AdminStudioApi.ts
  src/admins/features/animes/api/AdminVoiceActorApi.ts
  src/admins/features/animes/components/AdminCreateAnimeForm.tsx
  src/admins/features/animes/components/CreateSubCategoryButton.tsx
  src/admins/features/animes/components/ManageSubCategory/ManageSubCategory.tsx
  src/admins/features/animes/components/ManageSubCategory/ManageSubCategoryButton.tsx
  src/admins/features/animes/components/ManageSubCategory/ManageSubCategoryModal.tsx
  src/admins/features/animes/components/ManageSubCategory/ManageVoiceActorsModal.style.ts
  src/admins/features/animes/components/ManageSubCategory/ManageVoiceActorsModal.tsx
  src/admins/features/animes/hooks/useCreateGenre.ts
  src/admins/features/animes/hooks/useCreateOriginalAuthor.ts
  src/admins/features/animes/hooks/useCreateSeries.ts
  src/admins/features/animes/hooks/useCreateStudio.ts
  src/admins/features/animes/hooks/useCreateVoiceActor.ts
  src/admins/features/animes/hooks/useGenreManager.ts
  src/admins/features/animes/hooks/useGenres.ts
  src/admins/features/animes/hooks/useOriginalAuthors.ts
  src/admins/features/animes/hooks/useOriginalAuthorsManager.ts
  src/admins/features/animes/hooks/useSeries.ts
  src/admins/features/animes/hooks/useSeriesManager.ts
  src/admins/features/animes/hooks/useStudioManager.ts
  src/admins/features/animes/hooks/useStudios.ts
  src/admins/features/animes/hooks/useVoiceActorManager.ts
  src/admins/features/animes/hooks/useVoiceActors.ts
Labels: feature

#291 feat: 별점 평가 추가, 수정, 조회 구현
  src/features/reviews/api/review.ts
  src/features/reviews/api/reviewDev.ts
  src/features/reviews/components/ReviewRating/index.tsx
  src/features/reviews/hook/useEvaluation.ts
Labels: feature

#293 feat: 관리자 애니 목록 페이지네이션
  src/admins/features/animes/api/AdminAnimeApi.ts
  src/admins/features/animes/components/AdminAnimeList.tsx
  src/admins/features/animes/components/AdminAnimeSearch.tsx
  src/admins/features/animes/components/ManageSubCategory/ManageSubCategoryModal.tsx
  src/admins/features/animes/components/ManageSubCategory/ManageVoiceActorsModal.tsx
  src/admins/features/animes/hooks/useAnimes.ts
  src/admins/features/animes/hooks/useDeleteAnime.ts
  src/admins/libs/mantine/theme.ts
  src/types/business.d.ts
Labels: feature

#294 chore: SEO를 위한 기타 설정
  index.html
  public/apple-touch-icon.png
  public/robots.txt
  src/components/Head/index.tsx
  src/features/animes/routes/Detail/index.tsx
  src/features/common/routes/Error/404/index.tsx
  src/features/common/routes/Home/Discord/index.tsx
  src/features/common/routes/Home/index.tsx
Labels: chore

#295 feat: 메인 페이지 mock api 구현
  src/features/animes/api/AnimeApi.ts
  src/features/animes/api/mock/RecommendAnimes.json
  src/features/animes/api/mock/listOfRecentReviewed.json
  src/features/animes/api/mock/newestAnimes.json
  src/features/animes/api/mock/top10Animes.json
  src/features/animes/components/AnimeCarousel/AnimeCarouselLoading.tsx
  src/features/animes/components/AnimeCarousel/SlideItem.style.ts
  src/features/animes/components/AnimeCarousel/SlideItem.tsx
  src/features/animes/components/AnimeCarousel/index.tsx
  src/features/animes/components/AnimeCarousel/style.ts
  src/features/animes/components/AnimeRanking/AnimeRankingLoading.tsx
  src/features/animes/components/AnimeRanking/index.tsx
  src/features/animes/components/AnimeRanking/style.ts
  src/features/animes/components/AnimeSlide/AnimeSlideLoading.tsx
  src/features/animes/components/AnimeSlide/index.tsx
  src/features/common/routes/Home/NewestAnimes/index.tsx
  src/features/common/routes/Home/RecentReview/RecentReviewLoading.tsx
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/common/routes/Home/RecommendAnimes/index.tsx
  src/features/common/routes/Home/index.tsx
  src/features/common/routes/Home/style.ts
  src/features/reviews/api/mock/recentReview1.json
  src/features/reviews/api/mock/recentReview2.json
  src/features/reviews/api/mock/recentReview3.json
  src/features/reviews/api/mock/recentReviewOnlyOne.json
  src/features/reviews/api/review.ts
  src/features/reviews/api/reviewDev.ts
Labels: feature

#299 feat: 애니 상세페이지 사용자 평점 반영 및 애니 평균 별점 조회 구현
  src/features/animes/api/AnimeApi.ts
  src/features/animes/hooks/useAnime.ts
  src/features/animes/routes/Detail/Hero/index.tsx
  src/features/animes/routes/Detail/Ratings/index.tsx
  src/features/animes/routes/Detail/Ratings/style.ts
  src/features/animes/routes/Detail/index.tsx
  src/features/reviews/components/ReviewRating/index.tsx
  src/features/reviews/hook/useEvaluation.ts
Labels: feature

#296 feat: 애니 검색
  src/admins/libs/validation/animation.ts
  src/features/animes/components/AnimeCard/index.tsx
  src/features/animes/components/AnimeCardSkeleton/index.tsx
  src/features/animes/components/AnimeCardSkeleton/style.ts
  src/features/animes/hooks/useAnimes.ts
  src/features/animes/hooks/useFilterAnimes.ts
  src/features/animes/routes/Search/Searchbar/index.tsx
  src/features/animes/routes/Search/Searchbar/style.ts
  src/features/animes/routes/Search/SearchedAnimes/index.tsx
  src/features/animes/routes/Search/SearchedAnimes/style.ts
  src/features/animes/routes/Search/SuggestedAnimes/index.tsx
  src/features/animes/routes/Search/SuggestedAnimes/style.ts
  src/features/animes/routes/Search/index.tsx
  src/features/animes/routes/Search/style.ts
  src/features/common/routes/Search/Searchbar/index.tsx
  src/features/common/routes/Search/index.tsx
  src/routes/publicRoutes.tsx
Labels: feature, refactor

#302 fix: admin api path 오타
  src/admins/features/animes/api/AdminVoiceActorApi.ts
Labels: fix

#300 feat: 애니 리뷰 목록 조회 추가 및 변경 사항 적용
  src/contexts/OduckApiContext.tsx
  src/features/animes/routes/Detail/Reviews/Empty.style.ts
  src/features/animes/routes/Detail/Reviews/Empty.tsx
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/animes/routes/Detail/Reviews/style.ts
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/reviews/api/mock/anime_review_list1.json
  src/features/reviews/api/mock/anime_review_list2.json
  src/features/reviews/api/mock/anime_review_list3.json
  src/features/reviews/api/mock/anime_review_list4.json
  src/features/reviews/api/mock/recentReview1.json
  src/features/reviews/api/mock/recentReview2.json
  src/features/reviews/api/mock/recentReview3.json
  src/features/reviews/api/mock/recentReviewOnlyOne.json
  src/features/reviews/api/review.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/ReviewLikeButton.style.ts
  src/features/reviews/components/ReviewCard/ReviewLikeButton.tsx
  src/features/reviews/hook/useGetAnimeReviews.ts
  src/features/reviews/types/index.d.ts
  src/features/users/api/mock/review1.json
  src/features/users/api/mock/review2.json
  src/features/users/api/mock/review3.json
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
Labels: feature, refactor

#309 feat: 프로필 페이지 변경 사항 반영
  src/components/Layout/Sidebar.tsx
  src/features/animes/components/AnimeCard/index.tsx
  src/features/animes/hooks/useAnime.ts
  src/features/reviews/hook/useEvaluation.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.style.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.tsx
  src/utils/common.ts
Labels: feature, fix

#306 feat: 캐러셀 라이브러리 적용
  package-lock.json
  package.json
  src/features/animes/api/AnimeApi.ts
  src/features/animes/components/AnimeCard/index.tsx
  src/features/animes/components/AnimeCard/style.ts
  src/features/animes/components/AnimeCarousel/SlideItem.tsx
  src/features/animes/components/AnimeCarousel/index.tsx
  src/features/animes/components/AnimeMainCarousel/SliderItem.style.ts
  src/features/animes/components/AnimeMainCarousel/SliderItem.tsx
  src/features/animes/components/AnimeMainCarousel/index.tsx
  src/features/animes/components/AnimeMainCarousel/style.ts
  src/features/animes/components/AnimeRanking/index.tsx
  src/features/animes/components/AnimeRanking/style.ts
  src/features/animes/components/AnimeSlide/index.tsx
  src/features/animes/components/AnimeSlide/style.ts
  src/features/animes/routes/List/index.tsx
  src/features/animes/routes/Search/SearchedAnimes/index.tsx
  src/features/animes/routes/Search/SuggestedAnimes/index.tsx
  src/features/common/routes/Home/index.tsx
  src/libs/carousel/index.ts
Labels: feature

#310 feat: 리뷰 수정 구현
  src/features/animes/routes/Detail/Ratings/index.tsx
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/animes/routes/List/index.tsx
  src/features/bookmarks/hooks/useToggleBookmark.ts
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/reviews/api/mock/recentReview1.json
  src/features/reviews/api/mock/recentReview2.json
  src/features/reviews/api/mock/recentReview3.json
  src/features/reviews/api/mock/recentReviewOnlyOne.json
  src/features/reviews/api/review.ts
  src/features/reviews/api/reviewDev.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewRating/ShortReviewModal.tsx
  src/features/reviews/components/ReviewRating/index.tsx
  src/features/reviews/hook/useAddReview.ts
  src/features/reviews/hook/useEvaluation.ts
  src/features/reviews/hook/useGetAnimeReviews.ts
  src/features/reviews/hook/useGetEvaluation.ts
  src/features/reviews/hook/useReview.ts
  src/features/reviews/hook/useReviewForm.tsx
  src/features/reviews/types/index.d.ts
  src/features/users/api/mock/review1.json
  src/features/users/api/mock/review2.json
  src/features/users/api/mock/review3.json
  src/features/users/routes/Profile/TabMenu/BookmarkDeleteModal.tsx
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
  src/features/users/routes/Profile/TabMenu/SortBar.tsx
Labels: feature, refactor

#307 refactor: 애니 목록 페이지에서 카드 컴포넌트 변경 #305
  src/features/animes/components/AnimeCard/index.tsx
  src/features/animes/components/AnimeCard/style.ts
  src/features/animes/components/AnimeCardSkeleton/GridAnimeCardSkeleton.style.ts
  src/features/animes/components/AnimeCardSkeleton/GridAnimeCardSkeleton.tsx
  src/features/animes/components/AnimeCardSkeleton/index.tsx
  src/features/animes/components/AnimeCardSkeleton/style.ts
  src/features/animes/components/AnimeMainCarousel/style.ts
  src/features/animes/components/AnimeRanking/style.ts
  src/features/animes/components/AnimeSlide/index.tsx
  src/features/animes/components/AnimeSlide/style.ts
  src/features/animes/routes/Detail/LoadingReviews/style.ts
  src/features/animes/routes/List/index.tsx
  src/features/animes/routes/List/style.ts
  src/features/animes/routes/Search/SearchedAnimes/index.tsx
  src/features/animes/routes/Search/SearchedAnimes/style.ts
  src/features/animes/routes/Search/SuggestedAnimes/index.tsx
  src/features/animes/routes/Search/SuggestedAnimes/style.ts
Labels: refactor

#311 feat: 입덕 포인트 추가, 조회 구현
  src/features/reviews/api/review.ts
  src/features/reviews/api/reviewDev.ts
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewRating/ShortReviewModal.tsx
  src/features/reviews/hook/useAttractionPoint.ts
  src/features/reviews/hook/useReviewForm.tsx
  src/features/reviews/types/index.d.ts
Labels: feature, refactor

#313 feat: 마우스 leave 시, 내가 평가했던 별점으로 돌아가기 구현
  src/components/Rating/index.tsx
  src/features/reviews/components/ReviewRating/index.tsx
Labels: feature

#315 fix: 프로덕션 환경에서 프로필 페이지 새로고침 오류 테스트
  src/features/auth/contexts/AuthContext.tsx
  src/routes/privateRoutes.tsx
Labels: bug, chore

#320 fix: 로그인 상태에서 privatRoute 새로고침 시, 로그인 페이지로 이동하는 오류 수정
  src/features/auth/contexts/AuthContext.tsx
  src/features/auth/routes/Login/index.tsx
  src/routes/privateRoutes.tsx
Labels: fix
