Repository oduck-team/oduck-client, pull requests merged in 2023-09, with the labels that each got.

#94 feat: 애니메이션 상세 페이지 로직 일부 반영
  src/components/Drawer/index.tsx
  src/components/Drawer/style.ts
  src/components/Layout/Sidebar.tsx
  src/components/SectionDivider/index.tsx
  src/components/SectionDivider/style.ts
  src/config/index.ts
  src/features/animations/apis/getAnimation.ts
  src/features/animations/hooks/useAnimation.ts
  src/features/animations/routes/Detail.tsx
  src/features/animations/routes/Detail/Hero.style.ts
  src/features/animations/routes/Detail/Hero.tsx
  src/features/animations/routes/Detail/PlotAndInfo.style.ts
  src/features/animations/routes/Detail/PlotAndInfo.tsx
  src/features/animations/routes/Detail/Ratings.style.ts
  src/features/animations/routes/Detail/Ratings.tsx
  src/features/animations/routes/Detail/Reviews.tsx
  src/features/animations/routes/Detail/Section.tsx
  src/features/animations/routes/Detail/index.tsx
  src/features/animations/types/index.ts
  src/features/common/routes/500.tsx
  src/routes/publicRoutes.tsx
Labels: feature, refactor

#101 refactor: prop readonly 제거
  src/components/Avatar/index.tsx
  src/components/Backdrop/index.tsx
  src/components/Badge/index.tsx
  src/components/BottomNavigation/index.tsx
  src/components/BottomSheet/index.tsx
  src/components/Button/index.tsx
  src/components/CheckBox/index.tsx
  src/components/Drawer/index.tsx
  src/components/Layout/Menu.tsx
  src/components/Layout/Sidebar.tsx
  src/components/Modal/index.tsx
  src/components/ModalActions/index.tsx
  src/components/Progress/index.tsx
  src/components/Rating/index.tsx
  src/components/ResponsiveContainer/index.tsx
  src/components/Stat/index.tsx
  src/components/Tabs/index.tsx
  src/components/TextArea/index.tsx
  src/components/TextInput/index.tsx
  src/features/admin/components/Layout/Menu.tsx
  src/features/animations/components/AnimationRanking.tsx
  src/features/common/routes/Search.tsx
  src/features/reviews/components/ReviewLikeButton.tsx
  src/features/reviews/components/ReviewSimpleCard.tsx
Labels: refactor

#100 refactor: page 컴포넌트 파일 구조
  src/features/admin/animations/routes/Add/index.tsx
  src/features/admin/animations/routes/List/index.tsx
  src/features/admin/common/components/QuantityInput.tsx
  src/features/admin/common/routes/Dashboard/index.tsx
  src/features/common/routes/Error/404.tsx
  src/features/common/routes/Error/500.tsx
  src/features/common/routes/HelpDesk/index.tsx
  src/features/common/routes/Home/index.tsx
  src/features/common/routes/Search/index.tsx
  src/features/users/routes/Profile/index.tsx
  src/routes/publicRoutes.tsx
Labels: refactor

#95 feat: 애니메이션 리스트 페이지 퍼블리싱
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/style.ts
  src/components/Chip/ActionChip.style.ts
  src/components/Chip/ActionChip.tsx
  src/components/Chip/FilterChip.style.ts
  src/components/Chip/FilterChip.tsx
  src/components/Chip/SelectableChip.style.ts
  src/components/Chip/SelectableChip.tsx
  src/components/Chip/index.tsx
  src/features/animations/components/AnimationCard.style.ts
  src/features/animations/components/AnimationCard.tsx
  src/features/animations/routes/List.tsx
Labels: feature

#104 refactor: 애니 상세 페이지 코드 분리 (+ Modal 버그 수정, 개선)
  src/components/BottomSheet/index.tsx
  src/components/Drawer/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/components/ModalActions/index.tsx
  src/components/ModalActions/style.ts
  src/components/ModalContent/index.tsx
  src/components/ModalContent/style.ts
  src/components/Rating/index.tsx
  src/components/Tabs/style.ts
  src/features/animations/routes/Detail/Hero.style.ts
  src/features/animations/routes/Detail/Hero.tsx
  src/features/auth/components/LoginAlertModal.style.ts
  src/features/auth/components/LoginAlertModal.tsx
  src/features/bookmarks/components/BookmarkButton.style.ts
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/bookmarks/hooks/useBookmark.ts
  src/features/reviews/components/ReviewRating.tsx
  src/hooks/useScrollLock.ts
Labels: feature, fix, refactor

#106 feat: 커스텀 fetch #105
  src/lib/axios/index.ts
  src/lib/error/index.ts
  src/lib/fetch/http-request.ts
  src/lib/fetch/index.ts
  src/lib/fetch/type.ts
Labels: feature

#107 feat: Drawer 터치 슬라이드 닫기 구현
  src/components/Drawer/hooks/useDrawer.ts
  src/components/Drawer/index.tsx
Labels: feature

#110 feat: BottomSheet 핸들바
  src/components/Backdrop/style.ts
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/style.ts
  src/features/animations/routes/List.tsx
  src/hooks/useScrollLock.ts
Labels: feature

#109 feat: 고객센터 일부 기능 구현, 코드 분리, UI 수정
  src/components/TextArea/style.ts
  src/components/TextInput/style.ts
  src/features/common/routes/HelpDesk/Form.style.ts
  src/features/common/routes/HelpDesk/Form.tsx
  src/features/common/routes/HelpDesk/Select.style.ts
  src/features/common/routes/HelpDesk/Select.tsx
  src/features/common/routes/HelpDesk/Success.tsx
  src/features/common/routes/HelpDesk/index.tsx
  src/features/common/routes/HelpDesk/useForm.ts
Labels: feature, refactor

#112 fix: 애니 상세페이지 우측 여백
  src/features/animations/routes/Detail/Hero.style.ts
Labels: fix

#114 Feat: AnimatePortal 구현 및 test 환경
  package-lock.json
  package.json
  src/__test__/customRender.tsx
  src/components/BottomNavigation/index.test.tsx
  src/components/BottomNavigation/index.tsx
  src/components/BottomSheet/index.tsx
  src/components/Drawer/index.tsx
  src/components/Layout/Sidebar.tsx
  src/components/Modal/index.tsx
  src/components/Portal/AnimatePortal.test.tsx
  src/components/Portal/AnimatePortal.tsx
  src/components/Portal/index.test.tsx
  src/features/animations/routes/List.tsx
  src/hooks/useAuth.tsx
  src/hooks/useFetch.tsx
  tsconfig.json
  vite.config.ts
  vitest.setup.ts
Labels: refactor, test, chore

#117 feat: 로그인 디자인 반영, 로그인 리다이렉트 구현, 인증인가 관리
  src/App.tsx
  src/components/Badge/index.tsx
  src/components/Drawer/index.tsx
  src/components/Layout/Sidebar.style.ts
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/config/index.ts
  src/contexts/.gitkeep
  src/contexts/AuthContext.tsx
  src/contexts/index.ts
  src/features/.gitkeep
  src/features/animations/apis/getAnimation.ts
  src/features/animations/apis/getAnimations.ts
  src/features/animations/hooks/useAnimation.ts
  src/features/auth/components/LoginAlertModal.tsx
  src/features/auth/hooks/useLocalUser.ts
  src/features/auth/hooks/useLogin.ts
  src/features/auth/routes/Callback.tsx
  src/features/auth/routes/Callback/index.tsx
  src/features/auth/routes/Login.tsx
  src/features/auth/routes/Login/SocialGroup.style.ts
  src/features/auth/routes/Login/SocialGroup.tsx
  src/features/auth/routes/Login/index.tsx
  src/features/auth/routes/Login/style.ts
  src/features/auth/types/index.ts
  src/hooks/useAuth.tsx
  src/hooks/useAuthFetch.tsx
  src/hooks/useFetch.tsx
  src/hooks/useLocalStorage.test.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useRedirect.ts
  src/hooks/useScrollLock.ts
  src/lib/.gitkeep
  src/lib/fetch/http-request.ts
  src/lib/fetch/index.ts
  src/lib/fetch/type.ts
  src/routes/publicRoutes.tsx
Labels: feature, refactor, test

#120 refactor: useFetch 구현 내용 수정
  src/features/animations/hooks/useAnimation.ts
  src/hooks/useFetch.test.ts
  src/hooks/useFetch.tsx
Labels: refactor

#121 feat. 랜딩 페이지 기능 일부 구현
  src/features/auth/hooks/useSignUp.ts
  src/features/common/routes/Home/Discord.tsx
  src/features/common/routes/Home/NameModal.tsx
  src/features/common/routes/Home/RecentReview.tsx
  src/features/common/routes/Home/index.tsx
Labels: feature, refactor

#122 refactor: admin useFetch 적용 및 favicon 추가
  index.html
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/logo/logo-rect.png
  public/logo/logo.png
  public/site.webmanifest
  src/App.tsx
  src/components/DeferredComponent/index.test.tsx
  src/components/DeferredComponent/index.tsx
  src/components/Drawer/style.ts
  src/components/Layout/Menu.style.ts
  src/components/Layout/Menu.tsx
  src/components/Layout/Menus.style.ts
  src/components/Layout/Menus.tsx
  src/components/Layout/Navigation/NavigationContent.tsx
  src/components/Layout/Navigation/NavigationItem.tsx
  src/components/Layout/Navigation/index.tsx
  src/components/Layout/Sidebar.style.ts
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
  src/components/Loader/index.tsx
  src/components/Loader/style.ts
  src/features/admin/animations/apis/createAnimation.ts
  src/features/admin/animations/hooks/useAddAnimation.ts
  src/features/admin/animations/routes/Add/index.tsx
  src/features/admin/animations/routes/List/index.tsx
  src/features/admin/components/Layout/Menu.tsx
  src/features/admin/components/Layout/Profile.tsx
  src/features/admin/components/Layout/Sidebar.style.ts
  src/features/admin/components/Layout/Sidebar.tsx
  src/features/admin/components/Logo/index.tsx
  src/features/animations/hooks/useAnimations.ts
  src/features/animations/types/index.ts
  src/features/auth/routes/Callback/index.tsx
  src/lib/error/index.ts
  src/routes/index.tsx
  src/routes/privateRoutes.tsx
  src/routes/publicRoutes.tsx
Labels: refactor, chore

#129 feat: useDebounce 훅
  src/hooks/useDebounce.test.tsx
  src/hooks/useDebounce.ts
Labels: feature

#131 refactor: 애니 리스트 페이지 컴포넌트 위치 이동 #93
  src/features/animations/routes/List/index.tsx
Labels: refactor

#135 feat: 북마크(입덕하기) 추가 & 삭제 hook, useDebounce hook, Stat 디자인 변경
  src/components/Stat/index.tsx
  src/components/Stat/style.ts
  src/features/animations/routes/Detail/Hero.tsx
  src/features/animations/routes/Detail/index.tsx
  src/features/bookmarks/components/BookmarkButton.style.ts
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/bookmarks/hooks/useAddBookmark.ts
  src/features/bookmarks/hooks/useBookmark.ts
  src/features/bookmarks/hooks/useRemoveBookmark.ts
  src/features/reviews/components/ReviewRating.tsx
  src/hooks/useFetch.test.ts
  src/hooks/useFetch.tsx
Labels: feature, refactor

#139 refactor: view max-width
  src/components/BottomNavigation/style.ts
  src/components/Layout/index.tsx
  src/components/Stat/style.ts
  src/components/Tabs/style.ts
  src/features/animations/routes/Detail/Hero.tsx
  src/features/animations/routes/List/index.tsx
  src/features/auth/routes/Login/style.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: fix, refactor

#143 refactor: 스타일 변수명 변경
  src/components/Badge/index.tsx
  src/components/Badge/style.ts
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/components/Chip/ActionChip.style.ts
  src/components/Chip/ActionChip.tsx
  src/components/Chip/FilterChip.style.ts
  src/components/Chip/FilterChip.tsx
  src/components/Chip/SelectableChip.style.ts
  src/components/Chip/SelectableChip.tsx
  src/components/Chip/index.tsx
  src/components/Layout/Sidebar.tsx
  src/features/animations/components/AnimationCarousel.tsx
  src/features/animations/routes/Detail/Reviews.tsx
  src/features/animations/routes/List/index.tsx
  src/features/auth/components/LoginAlertModal.tsx
  src/features/auth/routes/Login/index.tsx
  src/features/common/routes/Home/RecentReview.tsx
  src/features/common/routes/Search/index.tsx
  src/features/reviews/components/ReviewMoreButton.tsx
Labels: refactor

#141 refactor: 모달 계열 back drop 구조 및 애니메이션 개선
  index.html
  src/components/Backdrop/index.tsx
  src/components/BottomSheet/hooks/useBottomSheet.ts
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/style.ts
  src/components/Button/style.ts
  src/components/Drawer/hooks/useDrawer.ts
  src/components/Drawer/index.tsx
  src/components/Drawer/style.ts
  src/components/Layout/Sidebar.tsx
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/components/Portal/AnimatePortal.test.tsx
  src/components/Portal/AnimatePortal.tsx
  src/components/Portal/index.test.tsx
  src/components/Portal/index.tsx
  src/features/animations/routes/List/index.tsx
  src/hooks/useDebounce.test.tsx
  src/hooks/useDebounce.ts
  src/hooks/useThrottle.test.tsx
  src/hooks/useThrottle.ts
  src/hooks/useWindowSize.test.tsx
  src/hooks/useWindowSize.ts
  src/styles/container.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/styles/zIndex.ts
  src/utils/.gitkeep
  src/utils/common.ts
Labels: fix, refactor

#146 feat: 공통 헤더 컴포넌트
  src/components/Layout/Header.style.ts
  src/components/Layout/Header.tsx
  src/features/animations/routes/List/index.tsx
  src/features/auth/routes/Login/index.tsx
  src/features/auth/routes/Login/style.ts
  src/features/common/routes/HelpDesk/Form.tsx
  src/features/common/routes/HelpDesk/Select.style.ts
  src/features/common/routes/HelpDesk/Select.tsx
  src/features/common/routes/HelpDesk/Success.tsx
  src/features/common/routes/Search/index.tsx
Labels: feature, refactor

#154 내 프로필 Stat Modal 구현
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/components/Stat/index.tsx
  src/features/auth/components/LoginAlertModal.tsx
  src/features/users/routes/Profile/AboutMe.tsx
  src/features/users/routes/Profile/StatModal.style.ts
  src/features/users/routes/Profile/StatModal.tsx
Labels: feature

#155 feat: 404 NotFound
  public/logo/logo-empty.png
  src/features/common/routes/Error/404.style.ts
  src/features/common/routes/Error/404.tsx
Labels: feature

#149 feat: axios 인스턴스
  package-lock.json
  package.json
  src/features/files/apis/uploadImage.ts
  src/hooks/useFetch.test.ts
  src/hooks/useFetch.tsx
  src/lib/error/index.ts
  src/libs/api/index.ts
  src/libs/error/index.ts
  src/libs/r2/index.ts
Labels: feature

#157 fix: 페이지 전환이 로딩 중일 경우 drawer가 닫히지 않는 현상
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
  src/features/animations/routes/List/index.tsx
Labels: fix

#161 style: Modal 등장 애니메이션 수정 #160
  src/components/Modal/index.tsx
Labels: fix

#164 feat: 프로필 수정 페이지 구현
  package-lock.json
  package.json
  src/components/Backdrop/index.tsx
  src/components/TextArea/style.ts
  src/components/TextInput/style.ts
  src/features/users/components/AvatarEditButton.style.ts
  src/features/users/components/AvatarEditButton.tsx
  src/features/users/components/ProfileArt.style.ts
  src/features/users/components/ProfileArt.tsx
  src/features/users/components/ProfileArtEditButton.style.ts
  src/features/users/components/ProfileArtEditButton.tsx
  src/features/users/components/ProfileAvatar.style.ts
  src/features/users/components/ProfileAvatar.tsx
  src/features/users/components/ProfileImageSection.style.ts
  src/features/users/components/ProfileImageSection.tsx
  src/features/users/components/ProfileSetupButton.style.ts
  src/features/users/components/ProfileSetupButton.tsx
  src/features/users/hooks/useEditForm.ts
  src/features/users/routes/Profile/AboutMe.style.ts
  src/features/users/routes/Profile/AboutMe.tsx
  src/features/users/routes/Profile/ProfileButton.tsx
  src/features/users/routes/Profile/ProfileSetupModal.style.ts
  src/features/users/routes/Profile/ProfileSetupModal.tsx
  src/features/users/routes/ProfileEdit/EditForm.style.ts
  src/features/users/routes/ProfileEdit/EditForm.tsx
  src/features/users/routes/ProfileEdit/index.tsx
  src/features/users/routes/ProfileEdit/style.ts
  src/routes/publicRoutes.tsx
  src/utils/common.ts
Labels: feature

#168 feat: 한 줄 리뷰 모달 퍼블리싱
  src/components/Modal/index.tsx
  src/features/auth/components/LoginAlertModal.tsx
  src/features/reviews/components/AttractionPoint.style.ts
  src/features/reviews/components/AttractionPoint.tsx
  src/features/reviews/components/ReviewRating.style.ts
  src/features/reviews/components/ReviewRating.tsx
  src/features/reviews/components/ShortReviewModal.style.ts
  src/features/reviews/components/ShortReviewModal.tsx
  src/features/reviews/components/SpoilerCheckBox.style.ts
  src/features/reviews/components/SpoilerCheckBox.tsx
Labels: feature, refactor

#175 refactor: UI 컴포넌트 `Container` -> `컴포넌트명Container`로 변경
  src/components/Avatar/index.tsx
  src/components/Avatar/style.ts
  src/components/Backdrop/index.tsx
  src/components/Backdrop/style.ts
  src/components/Badge/index.tsx
  src/components/Badge/style.ts
  src/components/BottomNavigation/index.tsx
  src/components/BottomNavigation/style.ts
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/style.ts
  src/components/BottomSheet/useBottomSheet.ts
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/components/CheckBox/index.tsx
  src/components/CheckBox/style.ts
  src/components/Chip/ActionChip.style.ts
  src/components/Chip/ActionChip.tsx
  src/components/Chip/FilterChip.style.ts
  src/components/Chip/FilterChip.tsx
  src/components/Chip/SelectableChip.style.ts
  src/components/Chip/SelectableChip.tsx
  src/components/Chip/index.tsx
  src/components/Drawer/index.tsx
  src/components/Drawer/style.ts
  src/components/Drawer/useDrawer.ts
  src/components/Layout/Header.style.ts
  src/components/Layout/Header.tsx
  src/components/Layout/Navigation/NavigationContent.style.ts
  src/components/Layout/Navigation/NavigationContent.tsx
  src/components/Layout/Navigation/NavigationItem.style.ts
  src/components/Layout/Navigation/NavigationItem.tsx
  src/components/Layout/Navigation/index.tsx
  src/components/Layout/Navigation/style.ts
  src/components/Layout/Sidebar.style.ts
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
  src/components/Layout/style.ts
  src/components/Loader/index.tsx
  src/components/Loader/style.ts
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/components/Progress/index.tsx
  src/components/Progress/style.ts
  src/components/Rating/index.tsx
  src/components/Rating/style.ts
  src/components/ResponsiveContainer/index.tsx
  src/components/ResponsiveContainer/style.ts
  src/components/SectionDivider/index.tsx
  src/components/SectionDivider/style.ts
  src/components/Stat/index.tsx
  src/components/Stat/style.ts
  src/components/Tabs/index.tsx
  src/components/Tabs/style.ts
  src/features/auth/routes/Login/index.tsx
  src/features/auth/routes/Login/style.ts
  src/features/common/routes/Error/404.style.ts
Labels: refactor

#177 refactor: users, reviews, auth 폴더의 최상위 `Container` -> `컴포넌트명Container` 변경
  src/features/auth/routes/Login/SocialGroup.style.ts
  src/features/auth/routes/Login/SocialGroup.tsx
  src/features/reviews/components/AttractionPoint.style.ts
  src/features/reviews/components/AttractionPoint.tsx
  src/features/reviews/components/ReviewLikeButton.style.ts
  src/features/reviews/components/ReviewLikeButton.tsx
  src/features/reviews/components/SpoilerCheckBox.style.ts
  src/features/reviews/components/SpoilerCheckBox.tsx
  src/features/users/components/AvatarEditButton.style.ts
  src/features/users/components/AvatarEditButton.tsx
  src/features/users/components/ProfileArt.style.ts
  src/features/users/components/ProfileArt.tsx
  src/features/users/components/ProfileArtEditButton.style.ts
  src/features/users/components/ProfileArtEditButton.tsx
  src/features/users/components/ProfileAvatar.style.ts
  src/features/users/components/ProfileAvatar.tsx
  src/features/users/components/ProfileImageSection.style.ts
  src/features/users/components/ProfileImageSection.tsx
  src/features/users/components/ProfileSetupButton.style.ts
  src/features/users/components/ProfileSetupButton.tsx
  src/features/users/routes/Profile/ReviewList.style.ts
  src/features/users/routes/Profile/ReviewList.tsx
  src/features/users/routes/Profile/index.tsx
  src/features/users/routes/Profile/style.ts
Labels: refactor

#178 refactor: users, reviews, auth폴더의 컴포넌트 파일 구조 변경
  src/features/auth/components/LoginAlertModal/index.tsx
  src/features/auth/components/LoginAlertModal/style.ts
  src/features/auth/routes/Login/SocialGroup/index.tsx
  src/features/auth/routes/Login/SocialGroup/style.ts
  src/features/reviews/components/AttractionPoint/index.tsx
  src/features/reviews/components/AttractionPoint/style.ts
  src/features/reviews/components/ReviewCard/ActionBar.style.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/Animation.style.ts
  src/features/reviews/components/ReviewCard/Animation.tsx
  src/features/reviews/components/ReviewCard/ReviewComent.style.ts
  src/features/reviews/components/ReviewCard/ReviewComent.tsx
  src/features/reviews/components/ReviewCard/ReviewLikeButton.style.ts
  src/features/reviews/components/ReviewCard/ReviewLikeButton.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewCard/UserRating.style.ts
  src/features/reviews/components/ReviewCard/UserRating.tsx
  src/features/reviews/components/ReviewCard/index.tsx
  src/features/reviews/components/ReviewCard/style.ts
  src/features/reviews/components/ReviewRating/ShortReviewModal.style.ts
  src/features/reviews/components/ReviewRating/ShortReviewModal.tsx
  src/features/reviews/components/ReviewRating/SpoilerCheckBox.style.ts
  src/features/reviews/components/ReviewRating/SpoilerCheckBox.tsx
  src/features/reviews/components/ReviewRating/index.tsx
  src/features/reviews/components/ReviewRating/style.ts
  src/features/users/components/ProfileImageSection/AvatarEditButton.style.ts
  src/features/users/components/ProfileImageSection/AvatarEditButton.tsx
  src/features/users/components/ProfileImageSection/ProfileArt.style.ts
  src/features/users/components/ProfileImageSection/ProfileArt.tsx
  src/features/users/components/ProfileImageSection/ProfileArtEditButton.style.ts
  src/features/users/components/ProfileImageSection/ProfileArtEditButton.tsx
  src/features/users/components/ProfileImageSection/ProfileAvatar.style.ts
  src/features/users/components/ProfileImageSection/ProfileAvatar.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupButton.style.ts
  src/features/users/components/ProfileImageSection/ProfileSetupButton.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupModal.style.ts
  src/features/users/components/ProfileImageSection/ProfileSetupModal.tsx
  src/features/users/components/ProfileImageSection/index.tsx
  src/features/users/components/ProfileImageSection/style.ts
  src/features/users/routes/Edit/EditForm/index.tsx
  src/features/users/routes/Edit/EditForm/style.ts
  src/features/users/routes/Edit/index.tsx
  src/features/users/routes/Edit/style.ts
  src/features/users/routes/Profile/AboutMe/StatModal.style.ts
  src/features/users/routes/Profile/AboutMe/StatModal.tsx
  src/features/users/routes/Profile/AboutMe/index.tsx
  src/features/users/routes/Profile/AboutMe/style.ts
  src/features/users/routes/Profile/ReviewList/index.tsx
  src/features/users/routes/Profile/ReviewList/style.ts
  src/routes/publicRoutes.tsx
Labels: refactor
