Repository oduck-team/oduck-client, pull requests merged in 2023-08, with the labels that each got.

#2 feat: 프로젝트 세팅
  .eslintrc.cjs
  .gitignore
  .prettierrc.json
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: feature

#8 feat : 프로젝트 폴더구조
  src/assets/.gitkeep
  src/componsts/.gitkeep
  src/features/.gitkeep
  src/hooks/.gitkeep
  src/lib/.gitkeep
  src/routes/.gitkeep
  src/stores/.gitkeep
  src/utils/.gitkeep
Labels: feature

#12 feat: Head 컴포넌트
  package-lock.json
  package.json
  src/App.tsx
  src/components/Head/index.tsx
Labels: feature

#13 feat: 어드민 레이아웃 구현 (사이드바, 모바일 네비게이션)
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/features/admin/components/Layout/Menus.tsx
  src/features/admin/components/Layout/MobileNavigation.tsx
  src/features/admin/components/Layout/Profile.tsx
  src/features/admin/components/Layout/Sidebar.tsx
  src/features/admin/components/Layout/SidebarToggle.tsx
  src/features/admin/components/Layout/index.tsx
  src/features/admin/routes/Dashboard.tsx
Labels: feature

#19 feat: Portal 컴포넌트
  src/components/Portal/index.tsx
  src/types/index.ts
Labels: feature

#22 feat: 글로벌 스타일 ( typography, 리팩토링 )
  src/App.tsx
  src/assets/GlobalStyle.tsx
  src/assets/emotion.d.ts
  src/assets/font.css
  src/assets/reset.css
  src/assets/style.css
  src/assets/theme.ts
  src/main.tsx
  src/routes/Style.tsx
  src/styles/colors.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/styles/typography.ts
Labels: feature, refactor

#26 feat: Progress 컴포넌트
  src/components/Progress/index.tsx
  src/components/Progress/style.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: feature

#34 feat: Backdrop, BottomSheet 컴포넌트
  index.html
  src/components/Backdrop/index.tsx
  src/components/Backdrop/style.ts
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/style.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/styles/z-index.ts
Labels: feature

#33 feat: Input Text
  src/components/TextInput/index.tsx
  src/components/TextInput/style.ts
Labels: feature

#36 feat: 스크롤바 스타일
  src/assets/scrollbar.css
  src/assets/style.css
  src/features/admin/components/Layout/Menus.tsx
  src/features/admin/components/Layout/MobileNavigation.style.ts
  src/features/admin/components/Layout/MobileNavigation.tsx
  src/features/admin/components/Layout/Profile.style.ts
  src/features/admin/components/Layout/Profile.tsx
  src/features/admin/components/Layout/Sidebar.style.ts
  src/features/admin/components/Layout/Sidebar.tsx
  src/features/admin/components/Layout/SidebarToggle.style.ts
  src/features/admin/components/Layout/SidebarToggle.tsx
Labels: feature, refactor

#38 feat: MediaQuery
  src/styles/emotion.d.ts
  src/styles/mediaQuery.ts
  src/styles/theme.ts
Labels: feature

#39 feat: BottomNavigation 컴포넌트
  src/App.tsx
  src/assets/reset.css
  src/components/.gitkeep
  src/components/BottomNavigation/index.tsx
  src/components/BottomNavigation/style.ts
  src/components/Layout/index.tsx
  src/features/animations/routes/Detail.tsx
  src/features/animations/routes/List.tsx
  src/features/common/routes/404.tsx
  src/features/common/routes/Helpdesk.tsx
  src/features/common/routes/Home.tsx
  src/features/common/routes/Search.tsx
  src/features/users/routes/Profile.tsx
  src/routes/.gitkeep
Labels: feature

#40 feat: 아이콘 버튼
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/features/common/routes/HelpDesk.tsx
Labels: feature, fix

#43 feat: Drawer 컴포넌트 구현
  src/components/Drawer/index.tsx
  src/components/Drawer/style.ts
  src/styles/typography.ts
Labels: feature

#48 feat: 로그인 임시 화면
  src/App.tsx
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/components/ResponsiveContainer/index.tsx
  src/components/ResponsiveContainer/style.ts
  src/features/auth/routes/Login.tsx
  src/styles/container.ts
  src/styles/emotion.d.ts
  src/styles/mediaQuery.ts
  src/styles/theme.ts
  src/styles/z-index.ts
Labels: feature, refactor

#42 Feat: Stats 컴포넌트 구현
  src/components/Stat/index.tsx
  src/components/Stat/style.ts
Labels: feature, refactor

#50 feat: Avatar 컴포넌트
  src/components/Avatar/index.tsx
  src/components/Avatar/style.ts
  src/components/Badge/DotBadge.tsx
  src/components/Badge/NumberBadge.tsx
  src/components/Badge/index.tsx
  src/components/Badge/style.ts
Labels: feature

#51 feat: 랜딩페이지 상단 캐러셀
  src/features/home/components/Carousel.style.ts
  src/features/home/components/Carousel.tsx
  src/styles/z-index.ts
Labels: feature

#55 feat: 사용자 레이아웃 sidebar
  src/App.tsx
  src/components/Avatar/index.tsx
  src/components/BottomNavigation/index.tsx
  src/components/Button/index.tsx
  src/components/Layout/Menu.style.ts
  src/components/Layout/Menu.tsx
  src/components/Layout/Menus.style.ts
  src/components/Layout/Menus.tsx
  src/components/Layout/Sidebar.style.ts
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
Labels: feature, refactor

#58 feat: 랜딩페이지 인기 애니 랭킹
  src/features/home/components/Carousel.style.ts
  src/features/home/components/Ranking.style.ts
  src/features/home/components/Ranking.tsx
Labels: feature

#61 refactor: BottomNavigation 로직 이동
  src/components/BottomNavigation/index.tsx
  src/components/Layout/index.tsx
Labels: refactor

#62 Feat: Rating 컴포넌트
  src/components/Rating/index.tsx
  src/components/Rating/style.ts
  src/features/animations/components/Carousel.style.ts
  src/features/animations/components/Carousel.tsx
  src/features/animations/components/Ranking.style.ts
  src/features/animations/components/Ranking.tsx
  src/styles/z-index.ts
Labels: feature, refactor

#67 모달계열 컴포넌트 입장, 퇴장 애니메이션 적용
  package-lock.json
  package.json
  src/components/Backdrop/index.tsx
  src/components/Backdrop/style.ts
  src/components/Drawer/index.tsx
  src/components/Drawer/style.ts
Labels: feature

#65 style: BottomNavigation 스타일 변경
  src/components/BottomNavigation/style.ts
  src/components/Layout/index.tsx
Labels: refactor

#63 Chore: admin ui 라이브러리 변경 및 반영
  package-lock.json
  package.json
  src/features/admin/components/Layout/Menu.tsx
  src/features/admin/components/Layout/Menus.tsx
  src/features/admin/components/Layout/MobileNavigation.style.ts
  src/features/admin/components/Layout/MobileNavigation.tsx
  src/features/admin/components/Layout/Profile.style.ts
  src/features/admin/components/Layout/Profile.tsx
  src/features/admin/components/Layout/Sidebar.style.ts
  src/features/admin/components/Layout/Sidebar.tsx
  src/features/admin/components/Layout/SidebarToggle.style.ts
  src/features/admin/components/Layout/SidebarToggle.tsx
  src/features/admin/components/Layout/index.tsx
Labels: refactor, chore

#69 feat: CheckBox Component 구현
  src/components/CheckBox/index.tsx
  src/components/CheckBox/style.ts
Labels: feature

#71 feat: React lazy
  src/App.tsx
  src/components/Layout/index.tsx
  src/main.tsx
  src/routes/adminRoutes.tsx
  src/routes/index.tsx
  src/routes/privateRoutes.tsx
  src/routes/publicRoutes.tsx
Labels: feature

#68 feat: Modal 컴포넌트
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
  src/components/ModalActions/index.tsx
  src/components/ModalActions/style.ts
  src/components/ModalContent/index.tsx
  src/components/ModalContent/style.ts
Labels: feature

#72 feat: Chip
  src/components/Chip/ActionChip.style.ts
  src/components/Chip/ActionChip.tsx
  src/components/Chip/FilterChip.style.ts
  src/components/Chip/FilterChip.tsx
  src/components/Chip/SelectableChip.style.ts
  src/components/Chip/SelectableChip.tsx
  src/components/Chip/index.tsx
Labels: feature

#74 feat: 애니메이션 상세 페이지 퍼블리싱
  src/components/BottomNavigation/style.ts
  src/components/Progress/index.tsx
  src/components/Progress/style.ts
  src/components/Stat/index.tsx
  src/components/Stat/style.ts
  src/features/animations/routes/Detail.tsx
  src/features/reviews/components/LikeButton.style.ts
  src/features/reviews/components/LikeButton.tsx
  src/features/reviews/components/MoreButton.tsx
  src/features/reviews/components/SimpleReview.style.ts
  src/features/reviews/components/SimpleReview.tsx
Labels: feature

#77 feat: 랜딩페이지 퍼블리싱
  src/assets/font.css
  src/features/animations/components/Card.style.ts
  src/features/animations/components/Card.tsx
  src/features/animations/components/Slide.style.ts
  src/features/animations/components/Slide.tsx
  src/features/common/routes/Home.tsx
  src/features/reviews/components/CardReview.style.ts
  src/features/reviews/components/CardReview.tsx
Labels: feature

#76 feat: 검색 페이지 퍼블리싱
  src/features/common/routes/Search.tsx
Labels: feature

#78 style: 사용자 메뉴 Drawer 링크 폰트 사이즈 변경
  src/App.tsx
  src/components/Layout/Menu.style.ts
Labels: refactor

#83 refactor: 컴포넌트 이름 스타일
  src/components/Layout/Menus.tsx
  src/features/animations/components/AnimationCard.style.ts
  src/features/animations/components/AnimationCard.tsx
  src/features/animations/components/AnimationCarousel.style.ts
  src/features/animations/components/AnimationCarousel.tsx
  src/features/animations/components/AnimationRanking.style.ts
  src/features/animations/components/AnimationRanking.tsx
  src/features/animations/components/AnimationSlide.style.ts
  src/features/animations/components/AnimationSlide.tsx
  src/features/animations/components/Slide.tsx
  src/features/animations/routes/Detail.tsx
  src/features/common/routes/Home.tsx
  src/features/reviews/components/ReviewCard.style.ts
  src/features/reviews/components/ReviewCard.tsx
  src/features/reviews/components/ReviewLikeButton.style.ts
  src/features/reviews/components/ReviewLikeButton.tsx
  src/features/reviews/components/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewSimpleCard.style.ts
  src/features/reviews/components/ReviewSimpleCard.tsx
  src/features/users/routes/Profile.tsx
Labels: refactor

#84 feat: 검색 페이지 퍼블리싱 (검색바, 추천 애니 추가)
  src/components/Chip/SelectableChip.style.ts
  src/components/Chip/index.tsx
  src/features/common/routes/Search.tsx
Labels: feature

#90 style: TextInput 아이콘 관련 스타일 적용
  src/components/TextInput/index.tsx
  src/components/TextInput/style.ts
Labels: fix, refactor

#86 style: BottomNavgation 애니메이션
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/style.ts
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/components/Drawer/index.tsx
  src/components/Modal/index.tsx
  src/features/admin/common/routes/Dashboard.tsx
  src/features/admin/components/Layout/Menus.tsx
  src/features/admin/components/Layout/index.tsx
  src/routes/adminRoutes.tsx
  vite.config.ts
Labels: feature
