Repository oduck-team/oduck-client, pull requests merged in 2023-12, with the labels that each got.

#322 feat: 최근 한줄리뷰 페이지 퍼블리싱
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/reviews/routes/recent/index.tsx
  src/features/reviews/routes/recent/style.ts
  src/routes/publicRoutes.tsx
Labels: feature

#325 fix: 자기소개 더보기 버튼 반응형으로 변경
  src/features/users/hooks/useIntroduceReadMore.ts
  src/features/users/routes/Profile/AboutMe/index.tsx
  src/features/users/routes/Profile/AboutMe/style.ts
Labels: feature, fix

#327 fix: 프로필 수정 페이지 오류 및 개선사항 적용
  src/components/TextArea/index.tsx
  src/components/TextArea/style.ts
  src/features/auth/routes/Callback/index.tsx
  src/features/users/hooks/useEditForm.tsx
  src/features/users/routes/Edit/EditForm/index.tsx
Labels: feature, fix

#329 feat: 인앱 브라우저로 접속 시, 구글 로그인 불가 문구 추가
  src/features/auth/routes/Login/SocialGroup/index.tsx
  src/features/auth/routes/Login/SocialGroup/style.ts
Labels: feature

#330 feat: 프로필 페이지 한줄리뷰 api 적용
  src/components/Layout/index.tsx
  src/contexts/OduckApiContext.tsx
  src/features/bookmarks/components/BookmarkCardSkeleton.tsx
  src/features/reviews/components/ReviewCard/ActionBar.style.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/Animation.style.ts
  src/features/reviews/components/ReviewCard/Animation.tsx
  src/features/reviews/components/ReviewCard/ReviewCardSkeleton.tsx
  src/features/reviews/components/ReviewCard/style.ts
  src/features/users/api/profile.ts
  src/features/users/api/profileDev.ts
  src/features/users/hooks/useTabMenu.ts
  src/features/users/routes/Profile/ProfileLoading.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkList.tsx
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
  src/features/users/routes/Profile/TabMenu/index.tsx
Labels: feature

#332 fix: 프로필 페이지 user의 애니 개수를 가지고 오도록 변경
  src/features/users/routes/Profile/TabMenu/SortBar.tsx
  src/features/users/routes/Profile/TabMenu/index.tsx
Labels: fix

#334 feat: 메인페이지 변경사항 반영 및 버그 수정
  src/contexts/OduckApiContext.tsx
  src/features/animes/api/AnimeApi.ts
  src/features/animes/api/mock/listOfRecentReviewed.json
  src/features/animes/api/mock/top10Animes.json
  src/features/animes/components/AnimeCarousel/AnimeCarouselLoading.tsx
  src/features/animes/components/AnimeCarousel/SlideItem.style.ts
  src/features/animes/components/AnimeCarousel/SlideItem.tsx
  src/features/animes/components/AnimeCarousel/index.tsx
  src/features/animes/components/AnimeCarousel/style.ts
  src/features/animes/components/AnimeMainCarousel/SliderItem.style.ts
  src/features/animes/components/AnimeMainCarousel/SliderItem.tsx
  src/features/animes/components/AnimeMainCarousel/index.tsx
  src/features/animes/components/AnimeMainCarousel/style.ts
  src/features/animes/components/AnimeRanking/AnimeRankingLoading.tsx
  src/features/animes/components/AnimeRanking/index.tsx
  src/features/animes/components/AnimeRanking/style.ts
  src/features/animes/components/AnimeSlide/AnimeSlideLoading.tsx
  src/features/animes/components/AnimeSlide/style.ts
  src/features/common/routes/Home/Discord/style.ts
  src/features/common/routes/Home/RecentReview/style.ts
  src/features/common/routes/Home/RecentReviewImageCard/index.tsx
  src/features/common/routes/Home/RecentReviewImageCard/style.ts
  src/features/common/routes/Home/index.tsx
  src/features/common/routes/Home/style.ts
  src/features/reviews/api/mock/recentReviewCard.json
  src/features/reviews/api/review.ts
  src/features/reviews/api/reviewDev.ts
Labels: feature, fix

#335 feat: 메인페이지 폰트 스타일 변경
  src/features/animes/components/AnimeCard/style.ts
  src/features/animes/components/AnimeRanking/index.tsx
  src/features/animes/components/AnimeRanking/style.ts
  src/features/animes/components/AnimeSlide/style.ts
  src/features/common/routes/Home/RecentReview/style.ts
  src/features/common/routes/Home/RecentReviewImageCard/ImageCardLoading.tsx
  src/features/common/routes/Home/RecentReviewImageCard/index.tsx
  src/features/reviews/components/ReviewCard/Animation.style.ts
  src/features/reviews/components/ReviewCard/ReviewComent.style.ts
Labels: feature

#337 feat: 리뷰 좋아요 추가/삭제 구현
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/reviews/api/mock/recentReview1.json
  src/features/reviews/api/mock/recentReview2.json
  src/features/reviews/api/mock/recentReview3.json
  src/features/reviews/api/mock/recentReviewOnlyOne.json
  src/features/reviews/api/review.ts
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/hook/useGetIsLike.ts
  src/features/reviews/hook/useToggleLike.ts
  src/features/reviews/routes/recent/index.tsx
  src/features/users/api/profile.ts
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
Labels: feature, refactor

#341 chore: 메인 페이지 미구현 API 영역을 노출하지 않도록 변경
  src/features/common/routes/Home/index.tsx
Labels: chore

#342 feat: 애니 상세페이지 스타일 변경사항 적용 및 내 리뷰 영역 퍼블리싱
  src/components/Progress/index.tsx
  src/components/Progress/style.ts
  src/features/animes/routes/Detail/Hero/index.tsx
  src/features/animes/routes/Detail/Hero/style.ts
  src/features/animes/routes/Detail/PlotAndInfo/index.tsx
  src/features/animes/routes/Detail/PlotAndInfo/style.ts
  src/features/animes/routes/Detail/Ratings/index.tsx
  src/features/animes/routes/Detail/Ratings/style.ts
  src/features/reviews/components/ReviewRating/index.tsx
  src/features/reviews/components/ReviewRating/style.ts
  src/features/users/routes/Profile/AboutMe/index.tsx
  src/features/users/routes/Profile/AboutMe/style.ts
  src/hooks/useReadMoreText.ts
Labels: feature, refactor

#345 fix: 애니 리스트 페이지 무한 스크롤 발생 시, 스크롤 초기화 버그 수정
  src/features/animes/hooks/useAnimes.ts
  src/features/animes/hooks/useFilterAnimes.ts
  src/features/animes/routes/List/index.tsx
Labels: fix

#346 feat: 입덕포인트 수정 및 통계 조회 구현
  src/features/animes/api/AnimeApi.ts
  src/features/animes/hooks/useAnime.ts
  src/features/animes/routes/Detail/Ratings/index.tsx
  src/features/animes/routes/Detail/index.tsx
  src/features/reviews/api/review.ts
  src/features/reviews/components/ReviewCard/ReviewComent.tsx
  src/features/reviews/hook/useAttractionPoint.ts
  src/features/reviews/hook/useReviewForm.tsx
Labels: feature, fix, refactor

#349 로그인 페이지 높이 수정 및 mock api를 이용한 리뷰 삭제 구현
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/animes/routes/Detail/index.tsx
  src/features/auth/routes/Login/style.ts
  src/features/reviews/api/review.ts
  src/features/reviews/components/ReviewCard/ReviewComment.style.ts
  src/features/reviews/components/ReviewCard/ReviewComment.tsx
  src/features/reviews/components/ReviewCard/ReviewDeleteModal.style.ts
  src/features/reviews/components/ReviewCard/ReviewDeleteModal.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewCard/index.tsx
  src/features/reviews/hook/useGetAnimeReviews.ts
  src/features/reviews/hook/useReview.ts
Labels: feature, refactor
