Repository oduck-team/oduck-client, pull requests merged in 2023-10, with the labels that each got.

#176 refactor: 고객센터 form 구조 변경
  src/features/common/routes/HelpDesk/Form.tsx
  src/features/common/routes/HelpDesk/useForm.ts
Labels: refactor

#180 refactor: animations, common 폴더의 최상위 Container명 변경
  src/features/animations/components/AnimationCard.style.ts
  src/features/animations/components/AnimationCard.tsx
  src/features/animations/components/AnimationCarousel.style.ts
  src/features/animations/components/AnimationCarousel.tsx
  src/features/animations/components/AnimationRanking.style.ts
  src/features/animations/components/AnimationRanking.tsx
  src/features/animations/components/AnimationSlide.style.ts
  src/features/animations/components/AnimationSlide.tsx
  src/features/animations/routes/List/index.tsx
  src/features/common/routes/Error/404.style.ts
  src/features/common/routes/Error/404.tsx
  src/features/common/routes/HelpDesk/Form.tsx
  src/features/common/routes/HelpDesk/Select.style.ts
  src/features/common/routes/HelpDesk/Select.tsx
  src/features/common/routes/HelpDesk/Success.tsx
  src/features/common/routes/HelpDesk/index.tsx
  src/features/common/routes/Home/Discord.tsx
  src/features/common/routes/Home/NameModal.tsx
  src/features/common/routes/Home/RecentReview.style.ts
  src/features/common/routes/Home/RecentReview.tsx
  src/features/common/routes/Home/index.tsx
  src/features/common/routes/Search/index.tsx
Labels: refactor

#183 refactor: Checkbox
  src/components/CheckBox/index.tsx
  src/components/CheckBox/style.ts
Labels: refactor

#185 refactor: animations, common 폴더 컴포넌트 파일 구조 변경
  src/components/TextArea/style.ts
  src/features/animations/components/AnimationCard/index.tsx
  src/features/animations/components/AnimationCard/style.ts
  src/features/animations/components/AnimationCarousel/index.tsx
  src/features/animations/components/AnimationCarousel/style.ts
  src/features/animations/components/AnimationRanking/index.tsx
  src/features/animations/components/AnimationRanking/style.ts
  src/features/animations/components/AnimationSlide/index.tsx
  src/features/animations/components/AnimationSlide/style.ts
  src/features/animations/hooks/useFilterAnimations.ts
  src/features/animations/routes/List/Filter/index.tsx
  src/features/animations/routes/List/Filter/style.ts
  src/features/animations/routes/List/index.tsx
  src/features/animations/routes/List/style.ts
  src/features/common/hooks/useForm.ts
  src/features/common/routes/Error/404/index.tsx
  src/features/common/routes/Error/404/style.ts
  src/features/common/routes/HelpDesk/Form/index.tsx
  src/features/common/routes/HelpDesk/Form/style.ts
  src/features/common/routes/HelpDesk/Select/index.tsx
  src/features/common/routes/HelpDesk/Select/style.ts
  src/features/common/routes/HelpDesk/Success/index.tsx
  src/features/common/routes/HelpDesk/Success/style.ts
  src/features/common/routes/Home/Discord/index.tsx
  src/features/common/routes/Home/Discord/style.ts
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/common/routes/Home/RecentReview/style.ts
  src/features/common/routes/Search/Searchbar/index.tsx
  src/features/common/routes/Search/Searchbar/style.ts
  src/features/common/routes/Search/index.tsx
  src/features/common/routes/Search/style.ts
Labels: refactor

#184 feat: 다른 사용자 프로필 신고하기 퍼블리싱 및 SelectBox 컴포넌트 구현
  src/components/SelectBox/index.tsx
  src/components/SelectBox/style.ts
  src/features/users/components/ProfileImageSection/ProfileReportModal.style.ts
  src/features/users/components/ProfileImageSection/ProfileReportModal.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupButton.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupModal.tsx
  src/features/users/routes/Profile/AboutMe/index.tsx
Labels: feature

#186 fix: Stat 컴포넌트의 data 포맷 방식 변경
  src/components/Stat/index.tsx
  src/features/animations/routes/Detail/Hero.tsx
  src/features/users/routes/Profile/AboutMe/StatModal.tsx
  src/features/users/routes/Profile/AboutMe/index.tsx
Labels: fix

#188 refactor: ui components 폴더의 컴포넌트 파일 구조 변경
  src/components/Layout/Header/HeaderCenterSection.style.ts
  src/components/Layout/Header/HeaderCenterSection.tsx
  src/components/Layout/Header/HeaderLeftSection.style.ts
  src/components/Layout/Header/HeaderLeftSection.tsx
  src/components/Layout/Header/HeaderRightSection.style.ts
  src/components/Layout/Header/HeaderRightSection.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/Header/style.ts
  src/components/Modal/ModalActions.style.ts
  src/components/Modal/ModalActions.tsx
  src/components/Modal/ModalContent.style.ts
  src/components/Modal/ModalContent.tsx
  src/components/Modal/index.tsx
  src/components/Modal/style.ts
Labels: refactor

#190 refactor: icon 교체
  package-lock.json
  package.json
  src/App.tsx
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
  src/components/Rating/index.tsx
  src/features/animations/components/AnimationCard/index.tsx
  src/features/animations/components/AnimationCarousel/index.tsx
  src/features/animations/components/AnimationRanking/index.tsx
  src/features/animations/routes/List/Filter/index.tsx
  src/features/animations/routes/List/index.tsx
  src/features/auth/routes/Login/index.tsx
  src/features/common/routes/HelpDesk/index.tsx
  src/features/common/routes/Search/Searchbar/index.tsx
  src/features/reviews/components/ReviewCard/ReviewLikeButton.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
Labels: refactor, chore

#199 refactor: 랜딩 페이지 캐러셀 개선
  src/features/animations/components/AnimationCarousel/index.tsx
Labels: refactor

#200 feat: 공지사항 퍼블리싱 #196
  src/features/notices/routes/List/NoticeAccordion/index.tsx
  src/features/notices/routes/List/NoticeAccordion/style.ts
  src/features/notices/routes/List/index.tsx
  src/features/notices/routes/List/style.ts
  src/routes/publicRoutes.tsx
Labels: feature

#194 feat: 프로필 페이지 더보기 버튼 구현
  src/components/CheckBox/index.tsx
  src/components/SnackBar/index.tsx
  src/components/SnackBar/style.ts
  src/components/SnackBar/useSnackBar.tsx
  src/components/Stat/index.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.style.ts
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewRating/ShortReviewModal.tsx
  src/features/reviews/components/ReviewRating/SpoilerCheckBox.tsx
  src/features/users/components/DropDownModal/index.tsx
  src/features/users/components/DropDownModal/style.ts
  src/features/users/components/DropDownModal/useDropDownModal.ts
  src/features/users/components/ProfileImageSection/ProfileReportModal.style.ts
  src/features/users/components/ProfileImageSection/ProfileReportModal.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupButton.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupModal.tsx
  src/features/users/hooks/useIntroduceReadMore.ts
  src/features/users/routes/Profile/AboutMe/index.tsx
  src/features/users/routes/Profile/AboutMe/style.ts
Labels: feature

#202 refactor: 디자인 피드백 반영
  src/components/BottomSheet/index.tsx
  src/features/animations/routes/Detail/Ratings.style.ts
  src/features/animations/routes/Detail/Ratings.tsx
  src/features/animations/routes/List/style.ts
  src/features/common/routes/Search/Searchbar/style.ts
  src/features/notices/routes/List/NoticeAccordion/style.ts
  src/features/reviews/components/AttractionPoint/style.ts
  src/features/reviews/components/ReviewRating/ShortReviewModal.style.ts
Labels: fix, refactor

#204 refactor: Animation 👉 Anime
  src/components/Layout/index.tsx
  src/features/animations/components/AnimationCard/index.tsx
  src/features/animations/components/AnimationSlide/index.tsx
  src/features/animations/hooks/useAnimation.ts
  src/features/animations/hooks/useAnimations.ts
  src/features/animes/api/mock.ts
  src/features/animes/components/AnimeCard/index.tsx
  src/features/animes/components/AnimeCard/style.ts
  src/features/animes/components/AnimeCarousel/index.tsx
  src/features/animes/components/AnimeCarousel/style.ts
  src/features/animes/components/AnimeRanking/index.tsx
  src/features/animes/components/AnimeRanking/style.ts
  src/features/animes/components/AnimeSlide/index.tsx
  src/features/animes/components/AnimeSlide/style.ts
  src/features/animes/hooks/useFilterAnimes.ts
  src/features/animes/routes/Detail/Hero.style.ts
  src/features/animes/routes/Detail/Hero.tsx
  src/features/animes/routes/Detail/PlotAndInfo.style.ts
  src/features/animes/routes/Detail/PlotAndInfo.tsx
  src/features/animes/routes/Detail/Ratings.style.ts
  src/features/animes/routes/Detail/Ratings.tsx
  src/features/animes/routes/Detail/Reviews.style.ts
  src/features/animes/routes/Detail/Reviews.tsx
  src/features/animes/routes/Detail/Section.style.ts
  src/features/animes/routes/Detail/Section.tsx
  src/features/animes/routes/Detail/index.tsx
  src/features/animes/routes/Detail/style.ts
  src/features/animes/routes/List/Filter/index.tsx
  src/features/animes/routes/List/Filter/style.ts
  src/features/animes/routes/List/index.tsx
  src/features/animes/routes/List/style.ts
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/bookmarks/hooks/useAddBookmark.ts
  src/features/bookmarks/hooks/useRemoveBookmark.ts
  src/features/common/routes/Home/index.tsx
  src/features/common/routes/Search/index.tsx
  src/features/reviews/components/ReviewRating/index.tsx
  src/routes/publicRoutes.tsx
Labels: refactor

#205 모달 컴포넌트의 state가 유지되지 않도록 수정한다.
  src/components/Backdrop/index.tsx
  src/components/Modal/index.tsx
  src/components/SnackBar/index.tsx
  src/features/auth/components/LoginAlertModal/index.tsx
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewRating/ShortReviewModal.tsx
  src/features/reviews/components/ReviewRating/index.tsx
  src/features/users/components/DropDownModal/index.tsx
  src/features/users/components/ProfileImageSection/ProfileReportModal.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupButton.tsx
  src/features/users/routes/Profile/AboutMe/StatModal.tsx
  src/features/users/routes/Profile/AboutMe/index.tsx
Labels: fix

#207 fix: 애니메이션 리스트 페이지 Header, Tabs 고정
  src/features/animes/routes/List/style.ts
Labels: fix

#213 feat: 프로필 페이지 한줄리뷰, 입덕애니 퍼블리싱
  src/components/Layout/Sidebar.tsx
  src/features/reviews/components/ReviewCard/index.tsx
  src/features/reviews/components/ReviewCard/style.ts
  src/features/users/hooks/useSortBar.ts
  src/features/users/routes/Profile/ReviewList/style.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.style.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkList.tsx
  src/features/users/routes/Profile/TabMenu/Icons.tsx
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
  src/features/users/routes/Profile/TabMenu/SheetButton.style.ts
  src/features/users/routes/Profile/TabMenu/SheetButton.tsx
  src/features/users/routes/Profile/TabMenu/SortBar.style.ts
  src/features/users/routes/Profile/TabMenu/SortBar.tsx
  src/features/users/routes/Profile/TabMenu/index.tsx
  src/features/users/routes/Profile/TabMenu/style.ts
  src/features/users/routes/Profile/index.tsx
Labels: feature

#216 feat: react-query 설정
  package-lock.json
  package.json
  src/App.tsx
  src/libs/react-query/index.ts
Labels: feature

#217 style: 애니 상세 페이지 디자인 변경 반영
  src/contexts/AuthContext.tsx
  src/features/animes/routes/Detail/Hero/index.tsx
  src/features/animes/routes/Detail/Hero/style.ts
  src/features/animes/routes/Detail/PlotAndInfo/index.tsx
  src/features/animes/routes/Detail/PlotAndInfo/style.ts
  src/features/animes/routes/Detail/Ratings/index.tsx
  src/features/animes/routes/Detail/Ratings/style.ts
  src/features/animes/routes/Detail/Reviews.style.ts
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/animes/routes/Detail/Reviews/style.ts
  src/features/reviews/components/ReviewCard/style.ts
Labels: refactor

#219 fix: ios input, textarea 화면 자동 확대
  src/components/TextArea/index.tsx
  src/components/TextArea/style.ts
  src/components/TextInput/style.ts
  src/features/common/routes/HelpDesk/Form/style.ts
  src/features/common/routes/Search/Searchbar/style.ts
Labels: fix, refactor

#220 feat: `SelectBox`의 dropdown 구현
  src/components/SelectBox/index.tsx
  src/components/SelectBox/style.ts
  src/components/SelectBox/useSelectBox.ts
  src/features/users/components/ProfileImageSection/ProfileReportModal.tsx
Labels: feature

#224 feat: IntersectionObserver 훅
  src/hooks/useIntersectionObserver.ts
Labels: feature

#222 fix: useScrollLock UX 개선
  index.html
  src/components/Backdrop/BackdropPortal.tsx
  src/components/Backdrop/BackropPortal.style.ts
  src/components/Backdrop/index.tsx
  src/components/BottomSheet/useBottomSheet.ts
  src/components/Drawer/index.tsx
  src/components/Modal/index.tsx
  src/components/SelectBox/style.ts
  src/components/SelectBox/useSelectBox.ts
  src/features/auth/hooks/useLogin.ts
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewRating/ShortReviewModal.tsx
  src/features/users/components/DropDownModal/index.tsx
  src/features/users/components/DropDownModal/style.ts
  src/features/users/components/ProfileImageSection/ProfileReportModal.tsx
  src/features/users/components/ProfileImageSection/ProfileSetupButton.tsx
  src/features/users/routes/Profile/AboutMe/index.tsx
  src/hooks/useScrollLock.ts
Labels: fix

#228 feat: 개발용 api 구현
  src/App.tsx
  src/contexts/OduckApiContext.tsx
  src/features/users/api/mock/profile.json
  src/features/users/api/profile.ts
  src/features/users/api/profileDev.ts
  src/features/users/routes/Profile/index.tsx
  src/hooks/useApi.tsx
Labels: feature

#229 feat: 고객센터 약관 동의 및 context 추가
  src/components/CheckBox/index.tsx
  src/components/CheckBox/style.ts
  src/components/Layout/Header/HeaderCenterSection.style.ts
  src/components/Layout/Header/style.ts
  src/components/Loader/style.ts
  src/contexts/HelpDeskContext.tsx
  src/features/common/hooks/useForm.ts
  src/features/common/hooks/useInquiryForm.ts
  src/features/common/routes/HelpDesk/Form/index.tsx
  src/features/common/routes/HelpDesk/Form/style.ts
  src/features/common/routes/HelpDesk/index.tsx
  src/features/common/routes/HelpDesk/style.ts
  src/features/common/routes/Terms/Email/index.tsx
  src/features/common/routes/Terms/Email/style.ts
  src/routes/publicRoutes.tsx
Labels: feature, fix, refactor

#231 refactor: auth api
  src/App.tsx
  src/components/Layout/Sidebar.tsx
  src/contexts/OduckApiContext.tsx
  src/features/auth/api/AuthApi.ts
  src/features/auth/api/getAuthStatus.ts
  src/features/auth/api/logout.ts
  src/features/auth/api/socialLogin.ts
  src/features/auth/contexts/AuthContext.tsx
  src/features/auth/hooks/useAuth.tsx
  src/features/auth/hooks/useLogin.ts
  src/features/auth/routes/Callback/index.tsx
  src/features/auth/routes/Login/index.tsx
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/common/routes/Home/index.tsx
  src/features/reviews/components/ReviewRating/index.tsx
  src/features/users/routes/Profile/index.tsx
  src/libs/api/index.ts
  src/routes/privateRoutes.tsx
Labels: refactor

#236 feat: 스켈레톤 컴포넌트 #234
  src/components/Skeleton/index.tsx
  src/components/Skeleton/style.ts
Labels: feature

#235 feat: 회원 프로필 조회 api 데이터로 변경
  src/contexts/OduckApiContext.tsx
  src/features/animes/routes/Detail/Reviews/index.tsx
  src/features/common/routes/Home/RecentReview/index.tsx
  src/features/reviews/components/ReviewCard/ActionBar.tsx
  src/features/reviews/components/ReviewCard/Animation.style.ts
  src/features/reviews/components/ReviewCard/Animation.tsx
  src/features/reviews/components/ReviewCard/ReviewMoreButton.tsx
  src/features/reviews/components/ReviewCard/index.tsx
  src/features/users/api/mock/profile.json
  src/features/users/api/profile.ts
  src/features/users/api/profileDev.ts
  src/features/users/components/ProfileImageSection/ProfileAvatar.style.ts
  src/features/users/hooks/useEditForm.ts
  src/features/users/routes/Edit/EditForm/index.tsx
  src/features/users/routes/Edit/index.tsx
  src/features/users/routes/Profile/AboutMe/StatModal.tsx
  src/features/users/routes/Profile/AboutMe/index.tsx
  src/features/users/routes/Profile/TabMenu/ReviewList.tsx
  src/features/users/routes/Profile/TabMenu/index.tsx
  src/features/users/routes/Profile/index.tsx
  src/types/business.d.ts
  src/utils/common.ts
Labels: feature

#239 feat: 북마크 조회 cursor-based Pagination 및 정렬 기능 구현
  src/contexts/OduckApiContext.tsx
  src/features/users/api/mock/bookmark1.json
  src/features/users/api/mock/bookmark2.json
  src/features/users/api/mock/bookmark3.json
  src/features/users/api/profile.ts
  src/features/users/api/profileDev.ts
  src/features/users/hooks/useSortBar.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.style.ts
  src/features/users/routes/Profile/TabMenu/BookmarkCard.tsx
  src/features/users/routes/Profile/TabMenu/BookmarkList.tsx
  src/features/users/routes/Profile/TabMenu/SheetButton.tsx
  src/features/users/routes/Profile/TabMenu/SortBar.tsx
  src/features/users/routes/Profile/TabMenu/index.tsx
  src/features/users/routes/Profile/TabMenu/style.ts
  src/libs/react-query/index.ts
  src/types/business.d.ts
Labels: feature

#244 feat: 애니 입덕하기/입덕 취소
  src/components/Stat/index.tsx
  src/contexts/OduckApiContext.tsx
  src/features/bookmarks/api/BookmarkApi.ts
  src/features/bookmarks/components/BookmarkButton.tsx
  src/features/bookmarks/hooks/useAddBookmark.ts
  src/features/bookmarks/hooks/useBookmark.ts
  src/features/bookmarks/hooks/useToggleBookmark.ts
  src/features/users/api/profile.ts
  src/features/users/hooks/useTabMenu.ts
  src/libs/api/index.ts
  src/libs/error/index.ts
Labels: feature

#245 feat: 프로필 로딩 컴포넌트 구현
  src/components/Loader/index.tsx
  src/components/Loader/style.ts
  src/features/users/routes/Edit/ProfileEditLoading.tsx
  src/features/users/routes/Edit/index.tsx
  src/features/users/routes/Profile/ProfileLoading.tsx
  src/features/users/routes/Profile/TabMenu/index.tsx
  src/features/users/routes/Profile/index.tsx
Labels: feature

#252 refactor: 유저 상태 조회
  src/features/auth/api/AuthApi.ts
  src/features/auth/contexts/AuthContext.tsx
  src/features/auth/routes/Callback/index.tsx
  src/features/auth/routes/Login/style.ts
Labels: fix, refactor

#254 feat: ErrorBoundary로 오류 관리
  src/components/Error/ErrorBoundary.tsx
  src/features/common/routes/Error/404/index.tsx
  src/features/users/routes/Profile/index.tsx
  src/libs/api/index.ts
  src/routes/ErrorBoundaryLayout.tsx
  src/routes/publicRoutes.tsx
Labels: feature
